server:
  port: 8081

spring:
  application:
    name: notification
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/subscription?createDatabaseIfNotExist=true
    username: root
    password: root