server:
  port: 8081

spring:
  application:
    name: notification

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/subscription?createDatabaseIfNotExist=true
    username: root
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: iban@iban.com
    password: xptoiban2022
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true