server:
  port: 8080

spring:
  application:
    name: subscription
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/subscription?createDatabaseIfNotExist=true
    username: root
    password: root
